few_shots = [
    {
        "Question": "How many t-shirts do we have left for Nike in XS size and white color?",
        "SQLQuery": "SELECT SUM(stock_quantity) FROM t_shirts WHERE brand='Nike' AND color='White' AND size='XS'",
        "SQLResult": "Result",
        "Answer": "91",
    },
    {
        "Question": "How much is the total price of the inventory for all S-size t-shirts?",
        "SQLQuery": "SELECT SUM(price * stock_quantity) FROM t_shirts WHERE size='S'",
        "SQLResult": "Result",
        "Answer": "22292",
    },
    {
        "Question": "If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue will our store generate?",
        "SQLQuery": """
        SELECT SUM(a.total_amount * ((100 - COALESCE(d.pct_discount,0)) / 100))
        FROM (
            SELECT t_shirt_id, SUM(price * stock_quantity) AS total_amount
            FROM t_shirts
            WHERE brand='Levi'
            GROUP BY t_shirt_id
        ) a
        LEFT JOIN discounts d ON a.t_shirt_id = d.t_shirt_id
        """,
        "SQLResult": "Result",
        "Answer": "16725.4",
    },
    {
        "Question": "How much revenue will be generated by selling all Nike L-size t-shirts after discount?",
        "SQLQuery": """
        SELECT SUM(a.total_amount * ((100 - COALESCE(d.pct_discount,0)) / 100))
        FROM (
            SELECT t_shirt_id, SUM(price * stock_quantity) AS total_amount
            FROM t_shirts
            WHERE brand='Nike' AND size='L'
            GROUP BY t_shirt_id
        ) a
        LEFT JOIN discounts d ON a.t_shirt_id = d.t_shirt_id
        """,
        "SQLResult": "Result",
        "Answer": "290",
    }
]
